
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lenovo
 */
public class EmployeeScreen extends javax.swing.JFrame {
    employeeOperations operations = new employeeOperations();
     private Connection con = null;
    private Statement statement = null;//sql sorgularini calistirmak icin gerekli olan methodlar barindirmaktadir.
    private PreparedStatement preparedStatement = null;
    

    /**
     * Creates new form EmployeeScreen
     */
    public EmployeeScreen() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLabel = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        surnameLabel = new javax.swing.JLabel();
        departmanLabel = new javax.swing.JLabel();
        salaryLabel = new javax.swing.JLabel();
        id_field = new javax.swing.JTextField();
        name_field = new javax.swing.JTextField();
        surname_field = new javax.swing.JTextField();
        salary_field = new javax.swing.JTextField();
        departman_field = new javax.swing.JTextField();
        myInformationLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        password_field = new javax.swing.JTextField();
        username_field = new javax.swing.JTextField();
        messageBox = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        saveChangesButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Employee Screen");
        setLocation(new java.awt.Point(475, 200));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        nameLabel.setText("Name:");
        getContentPane().add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 111, 28));

        idLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        idLabel.setText("ID:");
        idLabel.setPreferredSize(new java.awt.Dimension(22, 20));
        getContentPane().add(idLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 65, 28));

        surnameLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        surnameLabel.setText("Surname:");
        getContentPane().add(surnameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 237, 28));

        departmanLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        departmanLabel.setText("Departman:");
        departmanLabel.setPreferredSize(new java.awt.Dimension(86, 20));
        getContentPane().add(departmanLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 237, 28));

        salaryLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        salaryLabel.setText("Salary:");
        salaryLabel.setPreferredSize(new java.awt.Dimension(50, 20));
        getContentPane().add(salaryLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 237, 28));

        id_field.setEditable(false);
        id_field.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getContentPane().add(id_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 166, 28));

        name_field.setEditable(false);
        name_field.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getContentPane().add(name_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 166, 28));

        surname_field.setEditable(false);
        surname_field.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getContentPane().add(surname_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 166, 28));

        salary_field.setEditable(false);
        salary_field.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getContentPane().add(salary_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 166, 28));

        departman_field.setEditable(false);
        departman_field.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getContentPane().add(departman_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 166, 28));

        myInformationLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        myInformationLabel.setText("INFORMATIONS");
        getContentPane().add(myInformationLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, -1, 28));

        passwordLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        passwordLabel.setText("Password:");
        getContentPane().add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 237, 28));

        usernameLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        usernameLabel.setText("Username:");
        usernameLabel.setPreferredSize(new java.awt.Dimension(78, 20));
        getContentPane().add(usernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 237, 28));

        password_field.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getContentPane().add(password_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 166, 28));

        username_field.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getContentPane().add(username_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 166, 28));

        messageBox.setForeground(new java.awt.Color(255, 0, 0));
        messageBox.setText("jLabel1");
        getContentPane().add(messageBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 280, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Documents\\NetBeansProjects\\EProject\\tesla.png")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 80, -1));

        saveChangesButton.setText("Save Changes");
        saveChangesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveChangesButtonActionPerformed(evt);
            }
        });
        getContentPane().add(saveChangesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, 120, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveChangesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveChangesButtonActionPerformed
        int id  = Integer.parseInt(id_field.getText());
        String new_username  = username_field.getText();
        String new_password = password_field.getText();
        operations.employeeSavingChanges(id, new_username, new_password);
        JOptionPane.showMessageDialog(this, "Updated username or password!");
    }//GEN-LAST:event_saveChangesButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void showInformation(int id){
//        String query = "Select * from calisanlar where id = ?";
    
        messageBox.setText("");
        
        String name = operations.employeeName(id);
        String surname = operations.employeeSurname(id);
        String departman = operations.employeeDepartman(id);
        String salary = operations.employeeSalary(id);
        String username = operations.employeeUsername(id);
        String password = operations.employeePassword(id);
        
        boolean wages = operations.employeeWages(id);
        
        
        id_field.setText(Integer.toString(id));
        name_field.setText(name);
        surname_field.setText(surname);
        departman_field.setText(departman);
        salary_field.setText(salary);
        username_field.setText(username);
        password_field.setText(password);
        if (wages == true){
            JOptionPane.showMessageDialog(this, "Bu ayin maasi hesabiniza yatirilmistir!!");
            
        }
        else{
            messageBox.setText("Henuz bu ayin maasi hesabiniza yatirilmamistir! ");
            
        }
        
        
    }
    
    
    
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel departmanLabel;
    private javax.swing.JTextField departman_field;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField id_field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel messageBox;
    private javax.swing.JLabel myInformationLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField name_field;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField password_field;
    private javax.swing.JLabel salaryLabel;
    private javax.swing.JTextField salary_field;
    private javax.swing.JButton saveChangesButton;
    private javax.swing.JLabel surnameLabel;
    private javax.swing.JTextField surname_field;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField username_field;
    // End of variables declaration//GEN-END:variables
}
