
import java.util.ArrayList;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lenovo
 */
public class ManagerScreen extends javax.swing.JFrame {
    DefaultTableModel model ;//create a table
    employeeOperations operations = new employeeOperations();

    /**
     * Creates new form ManagerScreen
     */
    public ManagerScreen() {
        //super(parent, modal);
        initComponents();
        model = (DefaultTableModel)employeeTable.getModel();//convert the employee table 
        showEmployees();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        employeeTable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        searchBar = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        name_field = new java.awt.TextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        surname_field = new java.awt.TextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        departman_field = new java.awt.TextField();
        salary_field = new java.awt.TextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        username_field = new java.awt.TextField();
        jLabel1 = new javax.swing.JLabel();
        password_field1 = new java.awt.TextField();
        adminCheckBox = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        payinWagesButton = new java.awt.Button();
        addEmployee = new java.awt.Button();
        updateEmployeeButton = new java.awt.Button();
        deleteEmployee = new java.awt.Button();
        jLabel10 = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manager Screen");
        setLocationByPlatform(true);
        setPreferredSize(new java.awt.Dimension(1000, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        employeeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Ad", "Soyad", "Departman", "Maas", "Username", "Password", "Admin"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        employeeTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                employeeTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(employeeTable);
        if (employeeTable.getColumnModel().getColumnCount() > 0) {
            employeeTable.getColumnModel().getColumn(0).setResizable(false);
            employeeTable.getColumnModel().getColumn(1).setResizable(false);
            employeeTable.getColumnModel().getColumn(2).setResizable(false);
            employeeTable.getColumnModel().getColumn(3).setResizable(false);
            employeeTable.getColumnModel().getColumn(4).setResizable(false);
            employeeTable.getColumnModel().getColumn(5).setResizable(false);
            employeeTable.getColumnModel().getColumn(6).setResizable(false);
            employeeTable.getColumnModel().getColumn(7).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 940, 250));

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel6.setText("Search:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 60, 33));

        searchBar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        searchBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBarActionPerformed(evt);
            }
        });
        searchBar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchBarKeyReleased(evt);
            }
        });
        getContentPane().add(searchBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 515, 33));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name_field.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        name_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_fieldActionPerformed(evt);
            }
        });
        jPanel1.add(name_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 180, 33));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Name:");
        jLabel7.setPreferredSize(new java.awt.Dimension(43, 17));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 95, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Surname");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 95, 20));

        surname_field.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        surname_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surname_fieldActionPerformed(evt);
            }
        });
        jPanel1.add(surname_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 180, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Departman:");
        jLabel4.setPreferredSize(new java.awt.Dimension(43, 17));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 112, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Salary:");
        jLabel2.setPreferredSize(new java.awt.Dimension(43, 17));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 95, 20));

        departman_field.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        departman_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departman_fieldActionPerformed(evt);
            }
        });
        jPanel1.add(departman_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 180, 30));

        salary_field.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        salary_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salary_fieldActionPerformed(evt);
            }
        });
        jPanel1.add(salary_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 180, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 210, 290));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Username:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 95, 20));

        username_field.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        username_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_fieldActionPerformed(evt);
            }
        });
        jPanel2.add(username_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 25, 190, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Password:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 95, 20));

        password_field1.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        password_field1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_field1ActionPerformed(evt);
            }
        });
        jPanel2.add(password_field1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 95, 190, 30));

        adminCheckBox.setText("Admin?");
        adminCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminCheckBoxActionPerformed(evt);
            }
        });
        jPanel2.add(adminCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 210, 210));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        payinWagesButton.setBackground(new java.awt.Color(0, 51, 102));
        payinWagesButton.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        payinWagesButton.setForeground(new java.awt.Color(255, 255, 255));
        payinWagesButton.setLabel("Pay Wages");
        payinWagesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payinWagesButtonActionPerformed(evt);
            }
        });
        jPanel3.add(payinWagesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 141, 33));

        addEmployee.setBackground(new java.awt.Color(0, 51, 102));
        addEmployee.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        addEmployee.setForeground(new java.awt.Color(255, 255, 255));
        addEmployee.setLabel("Add ");
        addEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmployeeActionPerformed(evt);
            }
        });
        jPanel3.add(addEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 141, 33));

        updateEmployeeButton.setBackground(new java.awt.Color(0, 51, 102));
        updateEmployeeButton.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        updateEmployeeButton.setForeground(new java.awt.Color(255, 255, 255));
        updateEmployeeButton.setLabel("Update");
        updateEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateEmployeeButtonActionPerformed(evt);
            }
        });
        jPanel3.add(updateEmployeeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 141, 33));

        deleteEmployee.setBackground(new java.awt.Color(153, 0, 0));
        deleteEmployee.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        deleteEmployee.setForeground(new java.awt.Color(255, 255, 255));
        deleteEmployee.setLabel("Delete");
        deleteEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteEmployeeActionPerformed(evt);
            }
        });
        jPanel3.add(deleteEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 141, 33));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, 180, 220));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Documents\\NetBeansProjects\\EProject\\tesla.png")); // NOI18N
        jLabel10.setText("jLabel9");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 0, 80, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void dynamicSearch(String search){
        TableRowSorter<DefaultTableModel> table = new TableRowSorter<DefaultTableModel>(model);
        employeeTable.setRowSorter(table);
        table.setRowFilter(RowFilter.regexFilter(search));
    }
    private void payinWagesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payinWagesButtonActionPerformed
        
        operations.payWages();
        JOptionPane.showMessageDialog(this, "Payed Wages !!");
        
    }//GEN-LAST:event_payinWagesButtonActionPerformed

    private void updateEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateEmployeeButtonActionPerformed

        
        String name = name_field.getText();
        String surname = surname_field.getText();
        String departman = departman_field.getText();
        String salary = salary_field.getText();
        String username = username_field.getText();
        String password = password_field1.getText();
//        boolean isadmin = adminCheckBox.isEnabled();

        
        int selectedRow = employeeTable.getSelectedRow();
        
        boolean isadmin =  adminCheckBox.isSelected();
//        boolean isAdmin = Boolean.parseBoolean(isadmin);

        
        if(selectedRow == -1){
            if(model.getRowCount() == 0){
                JOptionPane.showMessageDialog(this, "Empty Rows !");
            }
            else{
                JOptionPane.showMessageDialog(this, "Choose a Row! ");         
            }
        }
        else{
            int id = (int)model.getValueAt(selectedRow, 0);
            operations.updateEmployee(id , name , surname , departman , salary , username , password , isadmin);
            showEmployees();
            JOptionPane.showMessageDialog(this, " Guncelleme Yapildi ...") ;         
        }
        
        
    }//GEN-LAST:event_updateEmployeeButtonActionPerformed

    private void addEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmployeeActionPerformed
        
        
        String name = name_field.getText();
        String surname = surname_field.getText();
        String departman = departman_field.getText();
        String salary = salary_field.getText();
        String username = username_field.getText();
        String password = password_field1.getText();
        
        boolean isadmin =  adminCheckBox.isSelected();
        System.out.println(isadmin);
//        boolean isAdmin = Boolean.parseBoolean(isadmin);
        
//        boolean isadmin = adminCheckBox.isEnabled();
        
        operations.addEmployee(name, surname , departman , salary , username , password,  isadmin);
        showEmployees();
        
        JOptionPane.showMessageDialog(this, "Ekleme Basariyla Yapildi");
        
        
    }//GEN-LAST:event_addEmployeeActionPerformed

    private void deleteEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteEmployeeActionPerformed
        int selectedRow = employeeTable.getSelectedRow();
        
        if(selectedRow == -1){
            if(model.getRowCount() == 0){
                JOptionPane.showMessageDialog(this, "There is no employee!");
            }
            else{
                JOptionPane.showMessageDialog(this, "Choose a Row!");
            }
        }
        else{
            int id = (int) model.getValueAt(selectedRow, 0);
            operations.deleteEmployee(id);
            showEmployees();
            JOptionPane.showMessageDialog(this, "Delete successfully finished!");
        }
        
        
        
    }//GEN-LAST:event_deleteEmployeeActionPerformed

    private void departman_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departman_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departman_fieldActionPerformed

    private void salary_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salary_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salary_fieldActionPerformed

    private void username_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username_fieldActionPerformed

    private void name_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_fieldActionPerformed

    private void searchBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBarActionPerformed

    private void searchBarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchBarKeyReleased
        String search = searchBar.getText();
        dynamicSearch(search);
    }//GEN-LAST:event_searchBarKeyReleased

    private void employeeTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeeTableMouseClicked
        
        int selectedRow = employeeTable.getSelectedRow();
        String isadmin =  employeeTable.getValueAt(selectedRow, 7).toString();
        
        
        name_field.setText(model.getValueAt(selectedRow, 1).toString());
        surname_field.setText(model.getValueAt(selectedRow, 2).toString());
        departman_field.setText(model.getValueAt(selectedRow, 3 ).toString());
        salary_field.setText(model.getValueAt(selectedRow, 4).toString());
        username_field.setText(model.getValueAt(selectedRow, 5).toString());
        password_field1.setText(model.getValueAt(selectedRow, 6).toString());
        //isadmin_field.setText(model.getValueAt(selectedRow , 7) .toString());
        
        if(isadmin.equals("true")){
            adminCheckBox.setSelected(true);
        }
        else{
            adminCheckBox.setSelected(false);
        }
        
        
    }//GEN-LAST:event_employeeTableMouseClicked

    private void surname_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surname_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_surname_fieldActionPerformed

    private void password_field1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_field1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password_field1ActionPerformed

    private void adminCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminCheckBoxActionPerformed
        
        
        
    }//GEN-LAST:event_adminCheckBoxActionPerformed
    public void showEmployees(){
        model.setRowCount(0);//resets the old table
        ArrayList<Employee> employees = new ArrayList<Employee>();//create a  new arraylist
        
        employees = operations.bringEmployees();
        if(employees != null){
            for(Employee employee : employees){
                Object[] toAdd = {employee.getId() , employee.getName(), 
                    employee.getSurname(),  employee.getDepartman(),employee.getSalary(), employee.getUsername() , employee.getPassword() , employee.isIsadmin()};
                
                model.addRow(toAdd);
            }
        }
        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button addEmployee;
    private javax.swing.JCheckBox adminCheckBox;
    private java.awt.Button deleteEmployee;
    private java.awt.TextField departman_field;
    private javax.swing.JTable employeeTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.TextField name_field;
    private java.awt.TextField password_field1;
    private java.awt.Button payinWagesButton;
    private java.awt.TextField salary_field;
    private javax.swing.JTextField searchBar;
    private java.awt.TextField surname_field;
    private java.awt.Button updateEmployeeButton;
    private java.awt.TextField username_field;
    // End of variables declaration//GEN-END:variables
}
