
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lenovo
 */
public class SignInScreen extends javax.swing.JFrame {
    employeeOperations operations = new employeeOperations();
    ImageIcon imageBackground = new ImageIcon("signIn.jpg");

    /**
     * Creates new form SignInScreen
     */
    public SignInScreen() {
        
        initComponents();
        labelPic.setText("");
        this.setLocationRelativeTo(null);
        labelPic.setIcon(imageBackground);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tf_password = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        ButLogIn = new javax.swing.JButton();
        tf_username = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        labelPic = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sign In Screen");
        setLocation(new java.awt.Point(400, 300));
        setMinimumSize(new java.awt.Dimension(735, 324));
        getContentPane().setLayout(null);

        tf_password.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getContentPane().add(tf_password);
        tf_password.setBounds(200, 140, 183, 26);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Password:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 140, 104, 23);

        ButLogIn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ButLogIn.setText("Log In");
        ButLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButLogInActionPerformed(evt);
            }
        });
        getContentPane().add(ButLogIn);
        ButLogIn.setBounds(502, 104, 143, 38);

        tf_username.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tf_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_usernameActionPerformed(evt);
            }
        });
        getContentPane().add(tf_username);
        tf_username.setBounds(200, 90, 183, 28);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Username:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(81, 97, 104, 23);

        labelPic.setText("jLabel3");
        getContentPane().add(labelPic);
        labelPic.setBounds(0, 0, 723, 320);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_usernameActionPerformed

    private void ButLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButLogInActionPerformed
        String username = tf_username.getText();
        String password = new String(tf_password.getPassword());//onemli password stringe cevirme
        boolean signInSuccesfull = operations.signIn(username , password);
//        int sd = operations.idAssignment(username, password); 
//        System.out.println("id ====== " +sd);
       
        System.out.println("signInSuccessful == " + signInSuccesfull);
        int id = operations.idAssignment(username, password);//!!bu satiri sonradan ilk ikinci iften sonraya koy!!
        boolean isAdam = operations.is_admin(id);//calisacak mi test?
        System.out.println("isAdam == " + isAdam);
        if(signInSuccesfull){
            
            if(operations.is_admin(id)){
                ManagerScreen managerscreen = new ManagerScreen();
                setVisible(false);
                managerscreen.setVisible(true);
                //System.exit(0);
                
            }
            else{
                EmployeeScreen employeescreen = new EmployeeScreen();
                int idEmployee = operations.idAssignment(username, password);
//                operations.personAssignment(idEmployee);
                setVisible(false);
                employeescreen.showInformation(idEmployee);
                employeescreen.setVisible(true);
//                System.exit(0);
                
                
            }
            
            
            
        }
        else{
            JOptionPane.showMessageDialog(this, "You entered wrong username or password");
            
        }
        
        
    }//GEN-LAST:event_ButLogInActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignInScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignInScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignInScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignInScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignInScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButLogIn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelPic;
    private javax.swing.JPasswordField tf_password;
    private javax.swing.JTextField tf_username;
    // End of variables declaration//GEN-END:variables
}
